general:
  print_log_freq: 100
  num_works: 8
  seed: 2021
  grad_acc_step: 1
  fp16: True
  train_file: ./input/hogehoge/...
  output_dir: ./log_exp001
  train: True
  n_fold: 5
  trn_fold:
    - 0
    - 1
    - 2
    - 3
    - 4

# transformsは順番大事
transforms:
  train:
    - name : RandomCrop
      params: 
        height : 600
        weight : 600
    - name: HorizontalFlip
      params:
      p : 0.5
    - name: RandamRotate90
      params:
        p : 0.5
    - name: VerticalFlip
      params:
        p : 0.5
    - name: Normalize
      params:
        p : 1.0
        mean: [0.486, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    - name: ToTensorV2
      params:
        p : 1.0
  
  valid:
    - name: Resize
      params:
        height : 600
        weight : 600
    - name : Normalize
      params:
        p : 1.0
        mean: [0.486, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    - name : ToTensorV2
      params:
        p : 1.0
    

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

train:
  loss_function: BCEWithLogitsLoss
  patience: 5
  train_batch_size: 64
  val_batch_size: 128
  num_workers: 8
  epochs: 15

scheduler:
  name: CosineAnnealingLR
  params: 
    T_max: 15
    eta_min: 0.000001
    last_epoch: -1

optimizer:
  name: Adam
  params:
    lr: 0.0001
    weight_decay: 0.000001
    amsgrad: False


model:
  name: reset50
  pretrained: True
  class_num: 2



target_cols:
  - hoge
  - hoge1